site_name: NetMQ

pages:

- ['index.md',                         'Home']

- ['introduction.md',                  'Introduction']

- ['receiving-sending.md', 'Concepts', 'Receiving and Sending']
- ['message.md',           'Concepts', 'Messages']
- ['transports.md',        'Concepts', 'Transports']

- ['poller.md',            'Components', 'Poller']
- ['actor.md',             'Components', 'Actor']
- ['beacon.md',            'Components', 'Beacon']

# - ['stream.md',            'Components', 'Stream']
# - ['scheduler.md',         'Components', 'Scheduler']
# - ['devices.md',           'Components', 'Devices']

- ['request-response.md',  'Patterns', 'Request-Response']
- ['pub-sub.md',           'Patterns', 'Pub-Sub']
- ['push-pull.md',         'Patterns', 'Push-Pull']
- ['router-dealer.md',     'Patterns', 'Router-Dealer']
- ['xpub-xsub.md',         'Patterns', 'XSub-XPub']

theme: readthedocs
repo_url: https://github.com/zeromq/netmq/
